config/routes.rb
CookingWithRails::Application.routes.draw do
  resources :ingredients, :recipes
  root :to => 'recipes#index'

end

app/models/ingredient.rb
class Ingredient
  include Mongoid::Document

  # Ingredients must have unique names
  field :name, :type => String
  validates_presence_of   :name, :message        => 'Name cannot be blank'
  validates_uniqueness_of :name, :case_sensitive => false

  # Ingredients define whether or not they are vegetarian-friendly
  field :is_veg,      :type => Boolean, :default => false
  # Ingredients have a space for a description
  field :description, :type => String,  :default => ''

  def vegetarian?
    is_veg == true
  end

  # Serialize the object for API output
  acts_as_api
  api_accessible :public do |template|
    template.add :name
    template.add :description
    template.add :is_veg, :as => :vegetarian
  end
end

app/models/recipe.rb
class Recipe
  include Mongoid::Document

  # Define and validate a recipe name
  field :name, :type => String
  validates_presence_of   :name, :message        => 'Name cannot be blank'
  validates_uniqueness_of :name, :case_sensitive => false

  # Define description and direction fields
  field :description, :type => String, :default => ''
  field :directions,  :type => String, :default => ''

  # A Recipe embeds several RecipeIngredients
  embeds_many :recipe_ingredients

  # Determine if a Recipe is vegetarian based on
  # whether or not its ingredients are all vegetarian
  def vegetarian?
    # Collect an array of the vegetarian state of each ingredient
    # and check it for any 'false' entries
    self.recipe_ingredients.collect do |ingredient|
      ingredient.vegetarian?
    end.include?( false ) == false
  end

  # Expose Recipes to the API
  acts_as_api
  api_accessible :public do |template|
    template.add :name
    template.add :description
    template.add :directions
    template.add :recipe_ingredients,  :as => :ingredients
    template.add 'vegetarian?'.to_sym, :as => :is_veg
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient
  include Mongoid::Document

  # Access name, description and vegetarian? properties through referenced Ingredient
  delegate :name, :description, 'vegetarian?'.to_sym, :to => :ingredient

  # Define a numeric quantity
  field :quantity, :type => Float
  validates_presence_of :quantity

  # Define a unit of measurement
  field :unit, :type => String
  validates_presence_of :unit

  # A RecipeIngredient refers to an existing Ingredient
  belongs_to :ingredient
  validates_presence_of :ingredient

  # Recipe Ingredients are embedded properties of Recipes
  embedded_in :recipe

  # Expose the RecipeIngredient to the API as a usable, dereferenced ingredient
  acts_as_api
  api_accessible :public do |template|
    template.add :quantity
    template.add :unit
    template.add :name
    template.add :description
    template.add 'vegetarian?'.to_sym, :as => :is_veg
  end
end

app/models/settings.rb
# This model exposes the application settings
class Settings < Settingslogic
  private
    def self.get_source
      application_config = ::File.join( ::Rails.root, 'config', 'application.yml' )
      if ::File.exist?( application_config )
        application_config
      elsif ::Rails.env == 'test' || ::Rails.env == 'heroku'
        "#{application_config}.example"
      else
        raise "Error: Could not find a working configuration for environment: #{::Rails.env}"
      end
    end

  source    get_source
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all

    respond_to do |format|
      format.html
      format.xml  { render_for_api :public, :xml  => @ingredients, :root => :ingredients }
      format.json { render_for_api :public, :json => @ingredients, :root => :ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html
      format.xml  { render_for_api :public, :xml  => @ingredient }
      format.json { render_for_api :public, :json => @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.html
      format.xml  { render_for_api :public, :xml  => @ingredient }
      format.json { render_for_api :public, :json => @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(params[:ingredient])

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :ok }
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html
      format.xml  { render_for_api :public, :xml  => @recipes, :location => :recipes }
      format.json { render_for_api :public, :json => @recipes, :location => :recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html
      format.xml  { render_for_api :public, :xml  => @recipe }
      format.json { render_for_api :public, :json => @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html
      format.xml  { render_for_api :public, :xml  => @recipe }
      format.json { render_for_api :public, :json => @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, :notice => 'Recipe was successfully created.' }
        format.xml  { render_for_api :public, :xml  => @recipe, :status => :created, :location => @recipe }
        format.json { render_for_api :public, :json => @recipe, :status => :created, :location => @recipe }
      else
        format.html { render :action => "new" }
        format.json { render :json => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, :notice => 'Recipe was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_topbar.html.haml
%div{ :class => 'navbar navbar-fixed-top', 'data-scrollspy' => 'scrollspy' }
  .navbar-inner
    .container
      %a{ :class => 'brand', :href => '#' }Cooking with Rails
      %ul.nav
        %li
          = link_to 'Recipes',     Recipe
        %li
          = link_to 'Ingredients', Ingredient

app/views/ingredients/_form.html.haml
= simple_form_for @ingredient, :validate => true, :html => { :class => 'form-horizontal' } do |f|
  = f.input  :name
  = f.input  :description, :as => :text, :input_html => { :rows => 5 }
  = f.input  :is_veg
  = f.button :submit

app/views/ingredients/edit.html.haml
%h1 Edit Ingredient

.span12
  = render 'form'

= link_to 'Show', @ingredient
\|
= link_to 'Back', ingredients_path

app/views/ingredients/index.html.haml
%h1 Ingredient Listing

%table{ :class => 'table-condensed table-striped' }
  %thead
    %tr
      %th Name
      %th Description
      %th Vegetarian
      %th
      %th

  - @ingredients.each do |ingredient|
    %tr
      %td= link_to ingredient.name, ingredient
      %td= ingredient.description.empty? ? 'n/a' : ingredient.description
      %td= ingredient.vegetarian? ? 'yes' : 'no'
      %td= link_to 'Edit',    edit_ingredient_path(ingredient)
      %td= link_to 'Destroy', ingredient, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Ingredient', new_ingredient_path

app/views/ingredients/new.html.haml
%h1 New Ingredient

.span12
  = render 'form'

= link_to 'Back', ingredients_path

app/views/ingredients/show.html.haml
%h1 Ingredient Details

%p#notice= notice

.span6
  %table
    %tr
      %th Name:
      %td= @ingredient.name
    %tr
      %th Description:
      %td= @ingredient.description.present? ? @ingredient.description : 'n/a'
    %tr
      %th Vegetarian:
      %td= @ingredient.vegetarian? ? 'yes' : 'no'
    %tr
      %th= link_to 'Edit', edit_ingredient_path(@ingredient)
      %td= link_to 'Back', ingredients_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title CookingWithRails
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render :partial => 'common/topbar'
    .page-body
      = yield

app/views/recipes/_form.html.haml
= simple_form_for @recipe, :validate => true, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :description, :as => :text, :input_html => { :rows => 5 }
  = f.input :directions,  :as => :text, :input_html => { :rows => 5 }
  = f.button :submit

app/views/recipes/edit.html.haml
%h1 Edit Recipe

= render 'form'

= link_to 'Show', @recipe
\|
= link_to 'Back', recipes_path

app/views/recipes/index.html.haml
%h1 Recipe Listing

%table{ :class => 'table-condensed table-striped' }
  %thead
    %tr
      %th Name
      %th Description
      %th Directions
      %th
      %th

  - @recipes.each do |recipe|
    %tr
      %td= link_to recipe.name, recipe
      %td= recipe.description
      %td= recipe.directions
      %td= link_to 'Edit', edit_recipe_path(recipe)
      %td= link_to 'Destroy', recipe, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Recipe', new_recipe_path

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'

= link_to 'Back', recipes_path

app/views/recipes/show.html.haml
%h1 Recipe Details

%p#notice= notice

%p
  %b Name:
  = @recipe.name
%p
  %b Description:
  = @recipe.description
%p
  %b Ingredients:
  %ul
  - @recipe.recipe_ingredients.each do |ingredient|
    %p.ingredient= "#{pluralize ingredient.quantity, ingredient.unit} #{ingredient.name}"
%p
  %b Directions:
  = @recipe.directions

= link_to 'Edit', edit_recipe_path(@recipe)
\|
= link_to 'Back', recipes_path